### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by anjibman** [anjibman/inventory-control#1]
- [ ] Column alignments e.g. Phone number centered
- [ ] Implement search feature
- [ ] Add left panel to display various actions that can be performed
